# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Club.create!(club_name: '学生自治会 執行委員会')
Club.create!(club_name: '学生ホール管理運営委員会')
Club.create!(club_name: '体育会本部')
Club.create!(club_name: '文化部連合')
Club.create!(club_name: 'サークル連合理事会')
Club.create!(club_name: '大学祭実行委員会')
Club.create!(club_name: '七夕祭実行委員会')
Club.create!(club_name: '新入生歓迎実行委員会')
Club.create!(club_name: '合気道連合')
Club.create!(club_name: 'アイスホッケー部')
Club.create!(club_name: 'アメリカンフットボール部')
Club.create!(club_name: '応援団')
Club.create!(club_name: '学術連合会')
Club.create!(club_name: '空手道部')
Club.create!(club_name: '弓道部')
Club.create!(club_name: '競技ダンス部(ALL)')
Club.create!(club_name: '剣道部')
Club.create!(club_name: '硬式野球部')
Club.create!(club_name: '硬式庭球部')
Club.create!(club_name: 'ゴルフ部')
Club.create!(club_name: '山岳部')
Club.create!(club_name: '自転車部')
Club.create!(club_name: '自動車部')
Club.create!(club_name: '柔道部')
Club.create!(club_name: '準硬式野球部')
Club.create!(club_name: '少林寺拳法部')
Club.create!(club_name: '水泳部')
Club.create!(club_name: 'スキー部')
Club.create!(club_name: '漕艇部')
Club.create!(club_name: 'ソフトテニス部')
Club.create!(club_name: '体操部')
Club.create!(club_name: '卓球部')
Club.create!(club_name: 'テコンドー部')
Club.create!(club_name: '軟式野球部')
Club.create!(club_name: '男子バスケットボール部')
Club.create!(club_name: '女子バスケットボール部')
Club.create!(club_name: 'バドミントン部')
Club.create!(club_name: '男子バレーボール部')
Club.create!(club_name: '女子バレーボール部')
Club.create!(club_name: 'パワーリフティング部')
Club.create!(club_name: 'ハンドボール部')
Club.create!(club_name: 'フライングディスク部')
Club.create!(club_name: 'ヨット部')
Club.create!(club_name: '陸上競技部')
Club.create!(club_name: 'ワンダーフォーゲル部')
Club.create!(club_name: 'AR部')
Club.create!(club_name: 'A.T.L')
Club.create!(club_name: 'English Speaking Society(ESS)')
Club.create!(club_name: '囲碁部')
Club.create!(club_name: '映画サークルKINO')
Club.create!(club_name: 'ボードゲーム研究会')
Club.create!(club_name: 'エリカ混声合唱団')
Club.create!(club_name: 'エンターテイメントサークルPal')
Club.create!(club_name: '大原こども会')
Club.create!(club_name: '学生教育研究会')
Club.create!(club_name: '学術会')
Club.create!(club_name: '管弦楽団')
Club.create!(club_name: '環境サークルnature')
Club.create!(club_name: 'クイズ研究会')
Club.create!(club_name: 'クラブミュージック研究会space')
Club.create!(club_name: 'グリークラブ')
Club.create!(club_name: '軽音楽部')
Club.create!(club_name: '劇団時計')
Club.create!(club_name: '古典ギター部')
Club.create!(club_name: '茶道研究会')
Club.create!(club_name: '三曲会')
Club.create!(club_name: '児童文化研究会')
Club.create!(club_name: '司法問題研究会')
Club.create!(club_name: '写真部')
Club.create!(club_name: 'JAZZ研究会')
Club.create!(club_name: '将棋部')
Club.create!(club_name: '人力飛行機研究会MaPPL')
Club.create!(club_name: '吹奏楽団')
Club.create!(club_name: '推理小説研究会')
Club.create!(club_name: 'Cap5')
Club.create!(club_name: 'フラッシュモブサークルCUBE')
Club.create!(club_name: '第三文明研究会')
Club.create!(club_name: 'Team "Lamp"')
Club.create!(club_name: 'TMU-SFC')
Club.create!(club_name: 'TMU Close up Magic Circle')
Club.create!(club_name: '鉄道研究会')
Club.create!(club_name: 'Dolce')
Club.create!(club_name: '軟式野球サークルRaD')
Club.create!(club_name: '美術部')
Club.create!(club_name: 'FINALFLASH')
Club.create!(club_name: 'フォークソング研究会')
Club.create!(club_name: '法学研究会')
Club.create!(club_name: '放送研究会')
Club.create!(club_name: 'マイクロコンピュータ研究会')
Club.create!(club_name: 'マンガ研究会')
Club.create!(club_name: 'めとぼけ')
Club.create!(club_name: 'Revolver')
Club.create!(club_name: '競技チアリーディングサークルWILD BOARS')
Club.create!(club_name: '学生社会科学研究会')
Club.create!(club_name: 'J-BOY')
Club.create!(club_name: '世界民謡研究会')
Club.create!(club_name: '星泳会')
Club.create!(club_name: '総合文化交流会mediaβ')
Club.create!(club_name: 'das Lied')
Club.create!(club_name: 'BBC(Beginners Basketball Club)')
Club.create!(club_name: '美術工芸研究会')
Club.create!(club_name: 'B類サッカー部')
Club.create!(club_name: 'B類テニス部')
Club.create!(club_name: 'B類バスケットボール部')
Club.create!(club_name: 'B類バドミントン部')
Club.create!(club_name: 'B類バレーボール部')
Club.create!(club_name: '文芸部')
Club.create!(club_name: '星の広場の会')
Club.create!(club_name: '唯物論研究会')

